### ISSUE TITLE
Bug no verso do cartão 

### ISSUE THREAD

**Issue by vcapretz** [pagarme/react-payment-card-component#16]
ao clicar no flip do cartão, durante a animação é possível ver o cvv e a tarja, mas quando a animação é concluída eles somem. 

OS: MacOS High Sierra 10.13 
Browser: Google Chrome 61.0.3163.100

<img width="373" alt="screen shot 2017-11-06 at 18 07 25" src="https://user-images.githubusercontent.com/14620121/32461744-fe5443d6-c31d-11e7-992d-6f20ac653311.png">

**Comment by thiagommedeiros** [comment]
Inspecionando o cartão pelo Browserstack com o OS e Browser mencionado notei que ao desativar a propriedade `transform: rotateY(180deg)` do seletor `.card .back`, a tarja e o cvv aparecem, mas invertidos. Ainda não sei como resolver, mas acho que essa info já pode ajudar em algo.
