### ISSUE TITLE
Sugestão: escrever readme pra esse repo

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/react-payment-card-component#36]
Seria legal ter um readme pro projeto ja desde o inicio pois assim todo mundo que chegar pra contribuir consegue entender qual é a interface desejada pro projeto. Escrever readme antes do código é sempre bom pq funciona mais ou menos como um "tdd" da sua interface, vc primeiro escreve como vc quer usar isso pra depois implementar.

**Comment by felquis** [comment]
Opa, senhor boas práticas aqui!! Muito boa a dica, recomendo forte :D
