### ISSUE TITLE
Sugestão: compactar imagens

### ISSUE THREAD

**Issue by LeoNero** [pagarme/react-payment-card-component#38]
## Description

Oi! Não sei se o create-react-app já faz isso por padrão (pelo que eu procurei não, mas talvez sim kkk), e não sei o quão necessário seria pro projeto, mas poderia ser legal compactar imagens...

Tem alguns loaders do webpack que fazem isso. Acho este o mais legal: https://github.com/tcoopman/image-webpack-loader

**Comment by vcapretz** [comment]
opa @LeoNero valeu a sugestão, a intenção é sim ter um compactador de imagens, vamos substituir as atuais que estão muito grandes por umas menores, mas estamos esperando as oficiais que vão vir de um pessoal do time de design. 

valeu a sugestão!

**Comment by LeoNero** [comment]
Mara @vcapretz xDD
