### ISSUE TITLE
Proposta de mudança na API do projeto

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/react-payment-card-component#44]
Atualmente nossa interface está assim:

``` jsx
<PaymentCard
   bank="bradesco"
   type="black-prime"
   brand="mastercard"
   number="4111111111111111"
   cvv="123"
   holderName="Fulano de Tal"
   expiration="12/19"
/>
```
Repare que o `type` está recebendo dois valores, o tipo do cartão na verdade é apenas `prime`, o `black` deveria estar em outra propriedade que eu ainda não sei qual nome deveria ter.

O problema da implementação atual é que recebemos 2 dados em um: `black-prime`, e para tratar esse dado a gente da um `split` e depois capitaliza o valor pra ficar `blackPrime`, será que isso não é overengineering? 

Dado que os cartões geralmente tem 3 atributos, exemplo: `Bradesco - Prime - Gold`, acredito que faz mais sentido criar uma nova propriedade, a questão é: qual o nome dessa propriedade que receberia valores como `black`, `gold`, `electron`, etc?

**Comment by thiagommedeiros** [comment]
Conversando com o @augusto-jm-amaral levantamos um questionamento: será que devemos alterar o que chamamos hoje de `type` para `model`? Ficaria então:

```
model: 'prime',
type: 'black'
```

O que vcs acham desses nomes?

**Comment by vcapretz** [comment]
concordo @thiagommedeiros, faz sentido! achei massa os nomes e a proposta

**Comment by augusto-jm-amaral** [comment]
Acho muito massa, isso vai facilitar o nosso teste A/B :smile:
