### ISSUE TITLE
Could not find package on the "npm" registry

### ISSUE THREAD

**Issue by haskellcamargo** [pagarme/react-payment-card-component#47]
## Description

Yarn and npm are failing when trying to install the module:

- Yarn
> `error Couldn't find package "react-payment-card-component" on the "npm" registry.`
![2017-11-28-142406_633x113_scrot](https://user-images.githubusercontent.com/7553006/33331118-dfff8a5e-d447-11e7-9def-d62428e4e29d.png)
- npm
![2017-11-28-142603_645x114_scrot](https://user-images.githubusercontent.com/7553006/33331181-175209c8-d448-11e7-831d-4e73bb9ba398.png)

Did you publish the project under this name?

**Comment by thiagommedeiros** [comment]
We have not published the project yet, so we need to add a disclaimer to the README.MD.

Thanks!
