### ISSUE TITLE
Criar um CONTRIBUTING.md

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/react-payment-card-component#9]
Precisamos criar um `CONTRIBUTING.md` com instruções de como contribuir com o projeto:

- Como instalar e configurar o ambiente de dev
- Apresentar o board: https://github.com/pagarme/react-cards-component/projects/1
- Orientações de como começar uma task e abrir um PR

**Comment by vcapretz** [comment]
Podemos nos basear no arquivo do [pagarme-js](https://github.com/pagarme/pagarme-js/blob/master/.github/CONTRIBUTING.md)?

**Comment by thiagommedeiros** [comment]
@vcapretz Total!! =D
